# Generated by Django 3.0.5 on 2020-05-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherfunction',
            name='content',
            field=models.CharField(max_length=255, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='teacherfunction',
            name='title',
            field=models.CharField(max_length=30, verbose_name='title'),
        ),
    ]
