# Generated by Django 3.0.5 on 2020-05-11 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20200511_2339'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
