# Generated by Django 3.0.5 on 2020-05-11 15:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher', '0003_delete_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='MakeClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30, verbose_name='subject')),
                ('semester', models.CharField(max_length=10, verbose_name='semester')),
                ('abstract', models.CharField(max_length=100, verbose_name='abstract')),
                ('teacher', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Class',
        ),
    ]
