# Generated by Django 3.0.5 on 2020-05-12 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher', '0006_auto_20200512_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='makeclass',
            name='teacher',
        ),
        migrations.AddField(
            model_name='makeclass',
            name='teacher',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
