# Generated by Django 3.0.5 on 2020-05-24 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0069_auto_20200524_1558'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher', '0008_delete_makeclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_course', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='classroom.Class')),
                ('teacher', models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
