# Generated by Django 3.0.5 on 2020-05-24 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher', '0009_teachermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abstract', models.CharField(max_length=100, verbose_name='abstract')),
                ('slug', models.SlugField()),
                ('is_registered', models.BooleanField(default=False)),
                ('teacher', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='add_course',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='teacher.Course'),
        ),
    ]
