# Generated by Django 3.0.5 on 2020-05-24 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0010_auto_20200524_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
    ]
