# Generated by Django 3.0.5 on 2020-05-05 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_messagetostudent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagetostudent',
            name='message',
        ),
    ]
