# Generated by Django 3.0.5 on 2020-05-11 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_delete_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['-email']},
        ),
    ]
