# Generated by Django 3.0.5 on 2020-05-11 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20200511_2008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['-date_joined']},
        ),
    ]
