# Generated by Django 3.0.5 on 2020-05-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='is_registered',
            field=models.BooleanField(default=False, verbose_name='proceding'),
        ),
    ]
