# Generated by Django 3.0.5 on 2020-05-27 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20200526_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(error_messages={'unique': 'This course_name has been used, please use other course_name'}, max_length=50, unique=True),
        ),
    ]
