# Generated by Django 3.0.5 on 2020-05-28 07:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20200527_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
            ],
        ),
        migrations.AlterField(
            model_name='coursedetail',
            name='number',
            field=models.IntegerField(error_messages={'unique': 'You have already created , please use other number of this course'}, unique=True),
        ),
        migrations.CreateModel(
            name='OwnCourseDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(error_messages={'unique': 'You have already created , please use other number of this course'}, unique=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='添付ファイル')),
                ('course', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='course.OwnCourse')),
            ],
        ),
    ]
