# Generated by Django 3.0.5 on 2020-05-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20200528_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetail',
            name='number',
            field=models.IntegerField(),
        ),
    ]
