# Generated by Django 3.0.5 on 2020-05-30 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20200528_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owncoursedetail',
            name='course',
        ),
        migrations.DeleteModel(
            name='OwnCourse',
        ),
        migrations.DeleteModel(
            name='OwnCourseDetail',
        ),
    ]
