# Generated by Django 3.0.5 on 2020-05-30 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0007_auto_20200530_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycourse',
            name='is_course_registered',
        ),
        migrations.RemoveField(
            model_name='mycourse',
            name='course',
        ),
        migrations.AddField(
            model_name='mycourse',
            name='course',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='course.Course'),
        ),
        migrations.CreateModel(
            name='RegisterCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.BooleanField(default=False)),
                ('student_name', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='mycourse',
            name='name',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='course.RegisterCourse'),
        ),
    ]
