# Generated by Django 3.0.5 on 2020-05-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_auto_20200512_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='subject',
            field=models.IntegerField(choices=[(1, 'English'), (2, 'Japanese')]),
        ),
    ]
