# Generated by Django 3.0.5 on 2020-05-18 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_class_approved'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Connection',
        ),
    ]
