# Generated by Django 3.0.5 on 2020-05-18 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0011_register_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='options',
        ),
        migrations.AddField(
            model_name='register',
            name='options',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='classroom.Class'),
        ),
    ]
