# Generated by Django 3.0.5 on 2020-05-18 13:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classroom', '0014_register_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='student',
        ),
        migrations.AddField(
            model_name='register',
            name='students',
            field=models.ManyToManyField(related_name='register_students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='register',
            name='options',
        ),
        migrations.AddField(
            model_name='register',
            name='options',
            field=models.ManyToManyField(related_name='register_options', to='classroom.Class'),
        ),
    ]
