# Generated by Django 3.0.5 on 2020-05-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0019_class_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='tags',
            field=models.ManyToManyField(to='classroom.Tag'),
        ),
    ]
