# Generated by Django 3.0.5 on 2020-05-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0024_remove_class_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='subject',
            field=models.CharField(max_length=20, verbose_name='subject'),
        ),
    ]
