# Generated by Django 3.0.5 on 2020-05-18 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0027_remove_register_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='classes',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='classroom.Class'),
        ),
    ]
