# Generated by Django 3.0.5 on 2020-05-18 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classroom', '0030_auto_20200518_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='name',
        ),
        migrations.AddField(
            model_name='class',
            name='tags',
            field=models.ManyToManyField(to='classroom.Tag'),
        ),
        migrations.AddField(
            model_name='register',
            name='students',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tag',
            name='tag',
            field=models.CharField(default=False, max_length=20),
        ),
    ]
