# Generated by Django 3.0.5 on 2020-05-18 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0031_auto_20200519_0708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='subject',
        ),
    ]
