# Generated by Django 3.0.5 on 2020-05-18 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0032_remove_class_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
