# Generated by Django 3.0.5 on 2020-05-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0034_auto_20200519_0753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='classes',
        ),
        migrations.AddField(
            model_name='register',
            name='register',
            field=models.ManyToManyField(to='classroom.Class'),
        ),
    ]
