# Generated by Django 3.0.5 on 2020-05-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0037_auto_20200520_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='grades',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default=None),
        ),
        migrations.RemoveField(
            model_name='class',
            name='subjects',
        ),
        migrations.AddField(
            model_name='class',
            name='subjects',
            field=models.CharField(choices=[('Math', 'Math'), ('English', 'English'), ('Science', 'Science'), ('PE', 'PE'), ('Geography', 'Geography'), ('physics', 'Physics')], default=False, max_length=20),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
