# Generated by Django 3.0.5 on 2020-05-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0039_auto_20200520_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='semester',
            field=models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4'), ('summer vacation', 'summer vacation'), ('winter vacation', 'winter vacation')], default=False, max_length=20),
        ),
    ]
