# Generated by Django 3.0.5 on 2020-05-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0041_auto_20200520_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='grades',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default=False, max_length=1),
        ),
    ]
