# Generated by Django 3.0.5 on 2020-05-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0042_auto_20200520_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='slug',
            field=models.SlugField(default='1'),
            preserve_default=False,
        ),
    ]
