# Generated by Django 3.0.5 on 2020-05-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0044_class_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='description',
        ),
        migrations.AddField(
            model_name='class',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
    ]
