# Generated by Django 3.0.5 on 2020-05-21 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0045_auto_20200521_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='is_registered',
        ),
    ]
