# Generated by Django 3.0.5 on 2020-05-21 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0046_remove_class_is_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='descriptions',
            field=models.TextField(default=False),
        ),
    ]
