# Generated by Django 3.0.5 on 2020-05-21 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0047_class_descriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='descriptions',
        ),
    ]
