# Generated by Django 3.0.5 on 2020-05-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0052_order_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='slug',
            field=models.SlugField(default=False),
        ),
    ]
