# Generated by Django 3.0.5 on 2020-05-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0053_register_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
