# Generated by Django 3.0.5 on 2020-05-21 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0055_relationship'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Relationship',
        ),
    ]
