# Generated by Django 3.0.5 on 2020-05-21 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0057_auto_20200522_0203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='one_click_purchasing',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='stripe_customer_id',
        ),
    ]
