# Generated by Django 3.0.5 on 2020-05-23 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0060_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='is_date',
            field=models.DateField(auto_now_add=True, default='2020-05-23'),
            preserve_default=False,
        ),
    ]
