# Generated by Django 3.0.5 on 2020-05-24 06:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0065_relationship2_is_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='uploads/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='添付ファイル')),
                ('is_class', models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, to='classroom.Class')),
            ],
        ),
    ]
