# Generated by Django 3.0.5 on 2020-05-24 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0066_classdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classdetail',
            name='is_class',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='classroom.Class'),
        ),
    ]
