# Generated by Django 3.0.5 on 2020-05-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0067_auto_20200524_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='classdetail',
            name='name',
            field=models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4'), ('summer vacation', 'summer vacation'), ('winter vacation', 'winter vacation')], default=False, max_length=20),
        ),
    ]
