# Generated by Django 3.0.5 on 2020-05-24 14:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classroom', '0069_auto_20200524_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4'), ('summer vacation', 'summer vacation'), ('winter vacation', 'winter vacation')], default=False, max_length=20)),
                ('abstract', models.CharField(max_length=100, verbose_name='abstract')),
                ('subjects', models.CharField(choices=[('Math', 'Math'), ('English', 'English'), ('Science', 'Science'), ('PE', 'PE'), ('Geography', 'Geography'), ('physics', 'Physics')], default=False, max_length=20)),
                ('grades', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default=False, max_length=1)),
                ('slug', models.SlugField()),
                ('is_registered', models.BooleanField(default=False)),
                ('name', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='classroom.ClassroomTeacher')),
            ],
        ),
        migrations.CreateModel(
            name='CourseDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('pdf_file', models.FileField(upload_to='uploads/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='添付ファイル')),
                ('course', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='classroom.Course')),
                ('name', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='classroom.ClassroomTeacher')),
            ],
        ),
    ]
