# Generated by Django 3.0.5 on 2020-05-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0070_classroomteacher_course_coursedetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetail',
            name='test',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
