# Generated by Django 3.0.5 on 2020-05-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0071_coursedetail_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetail',
            name='test',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
