# Generated by Django 3.0.5 on 2020-05-24 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classroom', '0072_auto_20200524_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoomStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MyCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_add', models.DateTimeField(auto_now_add=True)),
                ('is_registered', models.BooleanField(default=False)),
                ('course', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='classroom.Course')),
                ('name', models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, to='classroom.ClassRoomStudent')),
            ],
        ),
    ]
