# Generated by Django 3.0.5 on 2020-05-25 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0074_auto_20200524_2344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=False)),
                ('course', models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, to='classroom.MyCourse')),
            ],
        ),
    ]
