# Generated by Django 3.0.5 on 2020-05-25 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0075_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='course',
            field=models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, to='classroom.CourseDetail'),
        ),
    ]
