# Generated by Django 3.0.5 on 2020-05-25 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0076_auto_20200525_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursedetail',
            name='test',
        ),
    ]
