# Generated by Django 3.0.5 on 2020-05-25 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0078_auto_20200525_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
