# Generated by Django 3.0.5 on 2020-05-25 14:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0082_score_result_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='test',
            new_name='test_course',
        ),
        migrations.RemoveField(
            model_name='coursedetail',
            name='name',
        ),
        migrations.AddField(
            model_name='course',
            name='course_name',
            field=models.CharField(default=999, max_length=50),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='mycourse',
            name='course',
        ),
        migrations.AddField(
            model_name='mycourse',
            name='course',
            field=models.ManyToManyField(default=False, to='classroom.Course'),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_file',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='テストファイル'),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_name',
            field=models.CharField(default=9999, max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SectionTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_test_name', models.CharField(max_length=50)),
                ('test_file', models.FileField(upload_to='uploads/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='章末テストファイル')),
                ('section_test_course', models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, to='classroom.Course')),
            ],
        ),
        migrations.CreateModel(
            name='MidMyCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='classroom.Course')),
                ('my_course', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='classroom.MyCourse')),
            ],
        ),
        migrations.CreateModel(
            name='FinalTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_test_name', models.CharField(max_length=50)),
                ('test_file', models.FileField(upload_to='uploads/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='修了テストファイル')),
                ('final_test_course', models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, to='classroom.Course')),
            ],
        ),
    ]
