# Generated by Django 3.0.5 on 2020-05-25 15:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0084_auto_20200526_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectiontest',
            name='test_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='章末テストファイル'),
        ),
    ]
