# Generated by Django 3.0.5 on 2020-05-25 15:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0085_auto_20200526_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finaltest',
            name='test_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='修了テストファイル'),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='テストファイル'),
        ),
    ]
