# Generated by Django 3.0.5 on 2020-05-25 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0086_auto_20200526_0010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mycourse',
            old_name='is_registered',
            new_name='is_course_registered',
        ),
    ]
