# Generated by Django 3.0.5 on 2020-05-25 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0089_auto_20200526_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycourse',
            name='name',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='classroom.ClassRoomStudent'),
        ),
    ]
