# Generated by Django 3.0.5 on 2020-05-25 16:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0091_auto_20200526_0125'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Result',
            new_name='SectionTestResult',
        ),
        migrations.RenameField(
            model_name='sectiontestresult',
            old_name='student',
            new_name='section_student',
        ),
        migrations.CreateModel(
            name='MiniTestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_score', models.PositiveIntegerField(default=False)),
                ('result_file', models.FileField(default=False, upload_to='uploads/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='テスト結果')),
                ('course', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='classroom.Test')),
                ('mini_student', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='classroom.ClassRoomStudent')),
            ],
        ),
    ]
