# Generated by Django 3.0.5 on 2020-05-25 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0092_auto_20200526_0133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='minitestresult',
            old_name='mini_student',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='sectiontestresult',
            old_name='section_student',
            new_name='student',
        ),
        migrations.AlterField(
            model_name='sectiontestresult',
            name='course',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='classroom.SectionTest'),
        ),
    ]
