# Generated by Django 3.0.5 on 2020-05-25 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0093_auto_20200526_0134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='minitestresult',
            old_name='student',
            new_name='is_student',
        ),
    ]
