# Generated by Django 3.0.5 on 2020-05-25 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0094_auto_20200526_0135'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MiniTestResult',
        ),
    ]
