# Generated by Django 3.0.5 on 2020-05-25 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0096_minitestresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SectionTestResult',
        ),
    ]
