# Generated by Django 3.0.5 on 2020-05-25 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0097_delete_sectiontestresult'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MiniTestResult',
            new_name='Result',
        ),
    ]
