# Generated by Django 3.0.5 on 2020-05-25 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0100_result_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, to='classroom.ClassRoomStudent')),
                ('result', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='classroom.Result')),
            ],
        ),
    ]
