# Generated by Django 3.0.5 on 2020-05-25 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0101_studenttestresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentTestResult',
        ),
    ]
