# Generated by Django 3.0.5 on 2020-05-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0103_auto_20200526_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='grades',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default=False, max_length=100),
        ),
    ]
