# Generated by Django 3.0.5 on 2020-05-26 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0104_auto_20200526_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursedetail',
            name='course',
        ),
        migrations.RemoveField(
            model_name='finaltest',
            name='final_test_course',
        ),
        migrations.RemoveField(
            model_name='midmycourse',
            name='course',
        ),
        migrations.RemoveField(
            model_name='midmycourse',
            name='my_course',
        ),
        migrations.RemoveField(
            model_name='mycourse',
            name='course',
        ),
        migrations.RemoveField(
            model_name='mycourse',
            name='name',
        ),
        migrations.RemoveField(
            model_name='result',
            name='course',
        ),
        migrations.RemoveField(
            model_name='result',
            name='student',
        ),
        migrations.RemoveField(
            model_name='sectiontest',
            name='section_test_course',
        ),
        migrations.RemoveField(
            model_name='test',
            name='test_course',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='CourseDetail',
        ),
        migrations.DeleteModel(
            name='FinalTest',
        ),
        migrations.DeleteModel(
            name='MidMyCourse',
        ),
        migrations.DeleteModel(
            name='MyCourse',
        ),
        migrations.DeleteModel(
            name='Result',
        ),
        migrations.DeleteModel(
            name='SectionTest',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
